In [1]:
import pathlib
import matplotlib.pyplot as plt
import mne
import numpy
import pandas

In [2]:
dir_path = pathlib.Path.home()/'OneDrive'/'gamma_control_data'
assert dir_path.exists()

In [7]:
rate_df = pandas.read_csv(dir_path/'correct_rate.csv', index_col=0)
rate_df

           Hit  False Alarm  Correct Reject      Miss      rate
4139  0.833333     0.100000        0.900000  0.166667  0.866667
4072  0.283333     0.300000        0.700000  0.716667  0.491667
4466  0.750000     0.366667        0.633333  0.250000  0.691667
4447  0.616667     0.333333        0.666667  0.383333  0.641667
4221  0.450000     0.400000        0.600000  0.550000  0.525000
4579  0.866667     0.066667        0.933333  0.133333  0.900000
4562  0.633333     0.316667        0.683333  0.366667  0.658333
4572  0.400000     0.300000        0.700000  0.600000  0.550000
4630  0.366667     0.150000        0.850000  0.633333  0.608333
4318  0.400000     0.316667        0.683333  0.600000  0.541667
4699  0.550000     0.266667        0.733333  0.450000  0.641667
4300  0.850000     0.133333        0.866667  0.150000  0.858333
4493  0.866667     0.033333        0.966667  0.133333  0.916667
4541  0.466667     0.383333        0.616667  0.533333  0.541667
4271  0.916667     0.033333        0.966667  0.083333  0.941667
4367  0.900000     0.100000        0.900000  0.100000  0.900000
4126  0.933333     0.033333        0.966667  0.066667  0.950000
4593  0.516667     0.533333        0.466667  0.483333  0.491667
4704  0.883333     0.033333        0.966667  0.116667  0.925000
4658  0.066667     0.133333        0.866667  0.933333  0.466667

In [9]:
answers_df = pandas.read_csv(dir_path/'answers.csv', index_col=0)
answers_df

,session_type,event_name,???,response,key,mouse_X,mouse_Y,error_code,reaction_time,session_type_name,outcome,experiment_id,experiment_date,id_date,block
5,9,response,NaN,Left,Pressed,348.0,-53.0,C,9771,deviant,Miss,4699,1019,4699_1019,1
11,7,response,NaN,Left,Pressed,348.0,-53.0,C,9196,deviant,Miss,4699,1019,4699_1019,1
17,5,response,NaN,Left,Pressed,348.0,-53.0,C,9783,standard,Correct Reject,4699,1019,4699_1019,1
23,2,response,NaN,Right,Pressed,348.0,-53.0,C,8532,standard,False Alarm,4699,1019,4699_1019,1
29,10,response,NaN,Right,Pressed,348.0,-53.0,C,8836,deviant,Hit,4699,1019,4699_1019,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,7,response,NaN,Right,Pressed,-5.0,314.0,C,7668,deviant,Hit,4300,721,4300_0721,2
221,1,response,NaN,Left,Pressed,-5.0,314.0,C,7766,standard,Correct Reject,4300,721,4300_0721,2
227,2,response,NaN,Left,Pressed,-5.0,314.0,C,7677,standard,Correct Reject,4300,721,4300_0721,2
233,4,response,NaN,Right,Pressed,-5.0,314.0,C,7678,standard,False Alarm,4300,721,4300_0721,2
239,9,response,NaN,Right,Pressed,-5.0,314.0,C,7781,deviant,Hit,4300,721,4300_0721,2